Resources:
  notesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.notes_table_name}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: notesId
          AttributeType: S
      KeySchema:
        - AttributeName: notesId
          KeyType: HASH
